# .github/release.yml

changelog:
    categories:
        - title: 🏕 Features
          labels:
              - "*"
          exclude:
              labels:
                  - dependencies
        - title: Bug Fixes
          labels:
              - bug
        - title: 👒 Dependencies
          labels:
              - dependencies
