coverage:
    paths:
        - /kover/reportDebug.xml
    badge:
        path: docs/coverage.svg
codeToTestRatio:
    badge:
        path: docs/ratio.svg
testExecutionTime:
    badge:
        path: docs/time.svg
summary:
    if: true
    hideFooterLink: true
comment:
    if: is_pull_request
    hideFooterLink: true
diff:
    datastores:
        - artifact://${GITHUB_REPOSITORY}
report:
    if: is_default_branch
    datastores:
        - artifact://${GITHUB_REPOSITORY}
