name: Bump up version

on:
    schedule:
        - cron: '0 14 * * *'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        timeout-minutes: 20
        permissions:
            contents: write
            pull-requests: write

        env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
            BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: ruby/setup-ruby@v1
              with:
                ruby-version: '3.2'
                bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            - name: Set up git
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
            - name: Bump up version
              run: bundle exec fastlane bump_up_version_code
            - name: Get latest tag
              id: tag-selector
              run: |
               git fetch --prune
               tag=$(git describe --tags `git rev-list --tags --max-count=1`)
               echo "tag=$tag" >> "$GITHUB_OUTPUT"
            - name: Create pull request
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                tag_name=${{ steps.tag-selector.outputs.tag }}
                BODY=$(gh api /repos/{owner}/{repo}/releases/generate-notes -f tag_name=$tag_name -f target_commitish='develop' --jq .body)
                gh pr create --base develop --title "Version Bump $tag_name" --body "$BODY"
