name: Bump up version

on:
    schedule:
        - cron: '0 14 * * *'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Bump up
        runs-on: ubuntu-latest
        timeout-minutes: 20
        permissions:
            contents: write
            pull-requests: write
            actions: write

        env:
            BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
            BASE_BRANCH: develop

        outputs:
            tag: ${{ steps.tag-selector.outputs.tag }}

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: ruby/setup-ruby@v1
              with:
                ruby-version: '3.2'
                bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            - name: Set up git
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
            - name: Bump up version
              run: bundle exec fastlane bump_up_version_code
            - name: Get latest tag
              id: tag-selector
              run: |
                git fetch --prune
                tag=$(git describe --tags `git rev-list --tags --max-count=1`)
                echo "tag=$tag" >> "$GITHUB_OUTPUT"
            - name: Set up version
              id: version-selector
              run: |
                version=${git branch --show-current | sed 's/night-release\///'}
                echo "version=$version" >> "$GITHUB_OUTPUT"
            - name: Create pull request
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                tag_name=${{ steps.tag-selector.outputs.tag }}
                title=:up: Version Bump ${{ steps.version-selector.outputs.title }}
                body=$(gh api /repos/{owner}/{repo}/releases/generate-notes -f tag_name=$tag_name -f target_commitish=${{ env.BASE_BRANCH }} --jq .body)
                gh pr create --base ${{ env.BASE_BRANCH }} --title $title --body "$body"

    release:
        name: Call release
        needs: build
        permissions:
            contents: write
            pull-requests: write

        uses: ./.github/workflows/release.yml
        with:
            tag: ${{ needs.build.outputs.tag }}
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
