name: Call workflow

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    call-workflow-passing-data:
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            config-path: .github/labeler.yml
        secrets: inherit
