name: Call workflow

on:
    workflow_dispatch:
    schedule:
        - cron: "20 10 * * *"
        - cron: "0 13 * * *"
        - cron: "30 13 * * *"
        - cron: "0 14 * * *"
        - cron: "30 14 * * *"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Step1
              run: echo Step1

    call-workflow-passing-data:
        name: Call reusable
        needs: build

        uses: ./.github/workflows/reusable-workflow.yml
        with:
            config-path: .github/labeler.yml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
