name: Call workflow

on:
    workflow_dispatch:

jobs:
    call-workflow-passing-data:
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            config-path: .github/labeler.yml
        secrets: inherit
