name: Call workflow

on:
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Step1
              run: echo Step1
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Dump job context
              env:
                JOB_CONTEXT: ${{ toJson(job) }}
              run: echo "$JOB_CONTEXT"

    call-workflow-passing-data:
        name: Call reusable
        needs: build

        uses: ./.github/workflows/reusable-workflow.yml
        with:
            config-path: .github/labeler.yml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
