name: Call workflow

on:
    push:
        branches: feature/reusable-workflow2

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    call-workflow-passing-data:
        name: Pass input and secrets to my-action
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/reusable-workflow.yml
              with:
                  config-path: .github/workflows/call-workflow.yml
                  #   secrets: inherit
