name: Call workflow

on:
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Step1
              run: echo Step1

    call-workflow-passing-data:
        name: Call reusable
        needs: build

        uses: ./.github/workflows/reusable-workflow.yml
        with:
            config-path: .github/labeler.yml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
