name: Nighty Build CI

on:
    schedule:
        - cron: "29 12 * * *"
    # workflow_dispatch:
    #     inputs:
    #         tags:
    #             description: "Input the version (tags) to release"
    #             required: true
    #             type: string

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Create git
              run: |
                  date > generated.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git switch -c feature/v1.0.0-8
                  git add .
                  git commit -m "Nighty Build"
                  git push origin -u HEAD
                  git tag v1.0.0-8
                  git push origin v1.0.0-8
            - name: Create pr
              run: |
                  gh pr create -B "develop" \
                  -t v1.0.0-8 \
                  -b "Nighty Build"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
