name: Nighty Build CI

on:
    # schedule:
    #     - cron: "29 12 * * *"
    workflow_dispatch:
        inputs:
            tags:
                description: "Input the version (tags) to release"
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Create git
              run: |
                  date > generated.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
              #   git switch -c feature/${{ inputs.tags }}
              #   git add .
              #   git commit -m "Nighty Build"
              #   git push origin -u HEAD
              #   git tag ${{ inputs.tags }}
              #   git push origin ${{ inputs.tags }}
              #   run: |
            #       git fetch --tags
            #       echo "tag=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"
            - name: Get Tag
              id: get_tag
              uses: actions/github-script@v7
              with:
                  result-encoding: string
                  retries: 3
                  script: |
                      console.log({ context.ref });
                      console.log({ context };
                      const tag = context.ref.replace('refs/tags/', '');
                      console.log(tag);
                      const result = github.rest.git.getTag({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            tag_sha: context.repo.
                          });
                          console.log(result);
            - name: Display Tag
              run: echo "The latest tag is ${{ steps.get_tag.outputs.tag }}"
            # - name: Create pr
            #   run: |
            #       gh pr create -B "develop" \
            #       -t ${{ inputs.tags }} \
            #       -b "Nighty Build"
            #   env:
            #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
