name: Nighty Build CI

on:
    schedule:
        - cron: "30 11 * * *"
        - cron: "0 12 * * *"
    workflow_dispatch:
        inputs:
            tags:
                description: "Input the version (tags) to release"
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Create git
              run: |
                  date > generated.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
