name: Nighty Build CI

on:
    push:
        branches:
            - develop
        paths-ignore:
            - "**.md"

    pull_request:
        branches:
            - develop
        paths-ignore:
            - "**.md"

    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: pr list
              run: |
                  date > generated.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git switch -c feature/example
                  git add .
                  git commit -m "Nighty Build"
                  git push origin -u feature/example
            - name: Create pr
              run: |
                  gh pr create -B "develop" \
                  -t "Nighty Build" \
                  -b "Nighty Build"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
