name: Nighty Build CI

on:
    push:
        branches:
            - develop
        paths-ignore:
            - "**.md"

    pull_request:
        branches:
            - develop
        paths-ignore:
            - "**.md"

    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  path: develop
            - name: Get Date
              id: date
              run: |
                  name=date
                  value="$(date +'%Y-%m-%d')"
                  echo "${name}=${value}" >> $GITHUB_OUTPUT
            - name: Print date
              run: |
                  date > generated.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git switch -c feature/example
                  git add .
                  git commit -m "Nighty Build"
                  git push origin -u feature/example
            - name: Get pr list
              id: pr
              run: |
                  name=list
                  pr_list=$(gh pr list --json number | jq '[.[].number]')
                  value=pr_list
                  echo "${name}=${value}" >> $GITHUB_OUTPUT
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: pr list
              run: |
                  echo ${{ steps.pr.outputs.list }}
            #   run: |
            #       date > generated.txt
            #       git config user.name github-actions
            #       git config user.email github-actions@github.com
            #       git switch -c feature/example-${{ steps.date.outputs.date }}
            #       git add .
            #       git commit -m "Nighty Build"
            #       git push origin -u feature/example
            # - name: Create pr
            #   run: |
            #       gh pr create -B "develop" \
            #       -t "Nighty Build" \
            #       -b "Nighty Build"
            #   env:
            #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # - name: set up JDK 17
            #   uses: actions/setup-java@v4
            #   with:
            #       java-version: "17"
            #       distribution: "temurin"
            #       cache: gradle

            # - name: Grant execute permission for gradlew
            #   run: chmod +x gradlew
            # - uses: actions/cache@v3
            #   with:
            #       path: |
            #           ~/.gradle/caches
            #           ~/.gradle/wrapper
            #       key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            #       restore-keys: |
            #           ${{ runner.os }}-gradle-
            # - name: Lint
            #   run: |
            #       ./gradlew ktlintCheck
            #       ./gradlew lint
            # - name: Test
            #   run: ./gradlew test
            # - name: Build with Gradle
            #   run: ./gradlew build
